### ISSUE TITLE
Connecting config variables as inputs to modules can cause segfaults on exit

### ISSUE THREAD

**Issue by killenb** [ChimeraTK/ApplicationCore#63] opened 2019-09-26 09:25 UTC
Context:
In the llrfctrl server there is a module ReferecePhaseMonitor. It creates input variables "/AdcBoardX/ChannelY/isReference" by having variable groups "AdcBoardX" which have the hierarchy modifier "moveToRoot". If this variable is only cabled to the CS, everything is working fine.

If, however, the variables "/AdcBoardX/ChannelY/isReference" are added the _base_config (where they should come from), the server/test is crashing with a segfault when shutting down. It seems the entitiy owners are not set correctly.

To reproduce the issue have a look at llrfctrl branch "issue5681" and run testReferencePhaseMonitor. It seems to be a race condition. When running in valgrind, which slows down the execution. the segfault does not appear.

stack trace:
```
#0  0x00007ffff60e4231 in std::_List_iterator<ChimeraTK::Module*>::operator++ (this=0x7fffffffd7f0) at /usr/include/c++/5/bits/stl_list.h:159
#1  0x00007ffff60e44ab in std::__cxx11::list<ChimeraTK::Module*, std::allocator<ChimeraTK::Module*> >::remove (this=0xd8f3e8, __value=@0x7fffffffd820: 0xd8f568) at /usr/include/c++/5/bits/list.tcc:291
#2  0x00007ffff60ddb91 in ChimeraTK::EntityOwner::unregisterModule (this=0xd8f388, module=0xd8f568) at /home/killenb/ApplicationCore/src/EntityOwner.cc:65
#3  0x00007ffff6196a12 in ChimeraTK::Module::~Module (this=0xd8f568, __in_chrg=<optimized out>) at /home/killenb/ApplicationCore/src/Module.cc:31
#4  0x00000000006b0232 in ChimeraTK::ModuleImpl::~ModuleImpl (this=0xd8f568, __in_chrg=<optimized out>) at /home/killenb/ChimeraTK_testinstall/include/ChimeraTK/ApplicationCore/ModuleImpl.h:22
#5  0x00000000006b0368 in ChimeraTK::VariableGroup::~VariableGroup (this=0xd8f568, __in_chrg=<optimized out>) at /home/killenb/ChimeraTK_testinstall/include/ChimeraTK/ApplicationCore/VariableGroup.h:49
#6  0x000000000081812e in std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ChimeraTK::VariableGroup>::~pair (this=0xd8f548, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/stl_pair.h:96
#7  0x00007ffff666b55c in __gnu_cxx::new_allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ChimeraTK::VariableGroup> >::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ChimeraTK::VariableGroup> > (this=0x7fffffffd91f, __p=0xd8f548) at /usr/include/c++/5/ext/new_allocator.h:124
#8  0x00007ffff665e241 in std::allocator_traits<std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ChimeraTK::VariableGroup> > >::destroy<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ChimeraTK::VariableGroup> > (__a=..., __p=0xd8f548) at /usr/include/c++/5/bits/alloc_traits.h:542
#9  0x00007ffff664c460 in std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ChimeraTK::VariableGroup>, true> > >::_M_deallocate_node (this=0xd755e0, 
    __n=0xd8f540) at /usr/include/c++/5/bits/hashtable_policy.h:1973
#10 0x00007ffff663cf88 in std::__detail::_Hashtable_alloc<std::allocator<std::__detail::_Hash_node<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ChimeraTK::VariableGroup>, true> > >::_M_deallocate_nodes (this=0xd755e0, 
    __n=0x0) at /usr/include/c++/5/bits/hashtable_policy.h:1986
#11 0x00007ffff6621236 in std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ChimeraTK::VariableGroup>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ChimeraTK::VariableGroup> >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::clear (this=0xd755e0)
    at /usr/include/c++/5/bits/hashtable.h:1914
#12 0x00007ffff661711e in std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ChimeraTK::VariableGroup>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ChimeraTK::VariableGroup> >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::~_Hashtable (this=0xd755e0, 
    __in_chrg=<optimized out>) at /usr/include/c++/5/bits/hashtable.h:1225
#13 0x00007ffff6605e68 in std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, ChimeraTK::VariableGroup, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, ChimeraTK::VariableGroup> > >::~unordered_map (this=0xd755e0, 
    __in_chrg=<optimized out>) at /usr/include/c++/5/bits/unordered_map.h:98
#14 0x00007ffff6621f44 in ChimeraTK::ModuleList::~ModuleList (this=0xd755e0, __in_chrg=<optimized out>) at /home/killenb/ApplicationCore/Modules/src/ConfigReader.cc:60
#15 0x00007ffff6621fa0 in std::default_delete<ChimeraTK::ModuleList>::operator() (this=0xbedac0 <theServer+1440>, __ptr=0xd755e0) at /usr/include/c++/5/bits/unique_ptr.h:76
#16 0x00007ffff6618174 in std::unique_ptr<ChimeraTK::ModuleList, std::default_delete<ChimeraTK::ModuleList> >::~unique_ptr (this=0xbedac0 <theServer+1440>, __in_chrg=<optimized out>) at /usr/include/c++/5/bits/unique_ptr.h:236
#17 0x00007ffff65fc870 in ChimeraTK::ConfigReader::~ConfigReader (this=0xbed8d0 <theServer+944>, __in_chrg=<optimized out>) at /home/killenb/ApplicationCore/Modules/include/ConfigReader.h:113
#18 0x0000000000747499 in llrfctrl::~llrfctrl (this=0xbed520 <theServer>, __in_chrg=<optimized out>) at /home/killenb/llrfctrl/include/llrfctrl.h:45
#19 0x00007fffed323ff8 in __run_exit_handlers (status=0, listp=0x7fffed6ae5f8 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true) at exit.c:82
#20 0x00007fffed324045 in __GI_exit (status=<optimized out>) at exit.c:104
#21 0x00007fffed30a837 in __libc_start_main (main=0x65a50c <main(int, char**)>, argc=1, argv=0x7fffffffdbc8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdbb8) at ../csu/libc-start.c:325
#22 0x0000000000637db9 in _start ()
```

**Comment by mhier** [comment] 2020-09-11 09:50
duplicate of #127

**Closed by mhier** 2020-09-11 09:50 UTC
Labels: bug
