### ISSUE TITLE
Check for race conditions in tests

### ISSUE THREAD

**Issue by mhier** [ChimeraTK/ApplicationCore#197] opened 2020-09-16 07:47 UTC
There are 3 tickets reporting race conditions in tests:

* #104 
* #147 
* #160 

Check whether they are still happening. Also check for potential unknown race conditions. Try to fix all found race conditions, close the tickets of those which cannot be reproduced.

**Comment by toseko** [comment] 2020-09-22 12:52
I am not able to reproduce issues with tests. All tests are always passing. I tested this on my local xenial. ctest was run in 10 instances and in parallel 'stress' command was used in couple configuration to provide extra load to the system. Tests run for couple hours without problems. Then I also run individual tests mentioned in the ticket (testHistory, testFanoutConnections, testFanoutConnections) also in couple of instances with different load - no errors. I also tried to run into error using Bionic Docker container. Still no errors observed. It could be that issues are gone with current version of libs. Closing the ticket.

**Closed by toseko** 2020-09-22 12:52 UTC
Labels: bug, readyForImplementation, selected
