### ISSUE TITLE
Connecting ApplicationModule to DeviceModule will lose pushType information from device module

### ISSUE THREAD

**Issue by phako** [ChimeraTK/ApplicationCore#42] opened 2019-06-13 14:02 UTC
Assuming the following code:
```
DeviceModulde dev;
ApplicationModule mod;
…
mod.connectTo(dev);
```

And also assuming that mod has a push-type input and dev a corresponding output, the current code will generate a poll-type output on the dev.

`VirtualModule::connectTo()` calls  `operator(std::string)` on the device module (see https://github.com/ChimeraTK/ApplicationCore/blob/master/src/VirtualModule.cc#L70) which generates poll-type by default (see https://github.com/ChimeraTK/ApplicationCore/blob/master/src/DeviceModule.cc#L37). The following `operator>>` call will then connect the poll-type dev variable to the push-type input of mod, even though the device would support that variable as push-type (e.g. being a DOOCS ZMQ variable)

**Comment by mhier** [comment] 2019-06-13 14:19
I think the problem is that we are currently trying to avoid using the catalogue in this case. The information of the UpdateMode (push or poll) cannot be reliably inferred at the moment. I think this is the point we need to rethink.

This could be done like this: In the above example (no trigger given in connectTo), all variables must be push-type. This is already now the case. If a trigger is given in connectTo, we could assume that all variables are poll-type.

This would be an interface change. It would require in many situations to clearly separate between push-type and poll-type variables and use two connectTo() statements. I would consider this a good thing nowadays. In the current situation mistakes could stay unnoticed, e.g. a variable which is assumed to be push-type but actually is poll-type would be silently read with the trigger - this could create race conditions.

We would need to be able to filter modules for read or write, because most device variables are poll-type read and push-type write. We could introduce similar functions to findTag(), e.g. findReadable() and findWriteable(), maybe also findPushType() and findPollType().

Any other thoughts about this?

**Comment by mhier** [comment] 2021-06-16 15:55
This won't be fixed (if it is even still the case), as one should not make such connections that way. Instead everything to a ControlSystemModule, e.g. by using the ConnectingDeviceModule.

**Closed by mhier** 2021-06-16 15:55 UTC
